### ISSUE TITLE
ApplicationKit中存在问题,导致在editor中编译后,会导致场景里有多个GlobalComponent

### ISSUE THREAD

**Issue by WakakaYixixi** [yuyang9119/UnityExtensions#2]
重现过程
1.在非运行状态下不停的重新编译脚本
2.启动游戏会发现所有tween运行速度变快,且和编译次数成正比
3.显示出GlobalComponent的GameObject发现场景里面每次编译就会多出一个
4.停止运行再次重新运行会恢复正常

分析原因
每次重新编译都会导致_globalGameObject与_globalComponent引用丢失,且再次调用Initialize()方法,由于引用丢失,Initialize()方法会生成新的GlobalComponent且旧的不会消失

建议
是否在GlobalComponent的OnEnable()中检测是否和_globalGameObject或者_globalComponent引用一致,不一致则删除

**Comment by yuyang9119** [comment]
改问题已修复。
